export const ERR = {
    UNKNOWN: 'UNKNOWN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_ROLE: 'INVALID_ROLE',
    OBJECT_NOT_FOUND: 'OBJECT_NOT_FOUND',
    OBJECT_IS_ALREADY_EXIST: 'OBJECT_IS_ALREADY_EXIST',
    INVALID_FORMAT: 'INVALID_FORMAT',
    INVALID_VERSION: 'INVALID_VERSION',
    INVALID_OBJECT_STATUS: 'INVALID_OBJECT_STATUS',

    INVALID_USERNAME_OR_PASSWORD: 'INVALID_USERNAME_OR_PASSWORD',
    REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
    REFRESH_TOKEN_IS_EXPIRED: 'REFRESH_TOKEN_IS_EXPIRED',

    OLD_PASSWORD_WRONG: 'OLD_PASSWORD_WRONG',
    INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
    EXT_IS_USED: 'EXT_IS_USED',


};

export default ERR;